### ISSUE TITLE
ImportError: cannot import name 'AcadosOcp'

### ISSUE THREAD

**Issue by MuhammadAlhaddad** [acados/acados#769]
Hi, I am new to acados. I have followed the instructions to download acados and want to run python examples:
```
git clone https://github.com/acados/acados.git
cd acados
git submodule update --recursive --init
mkdir -p build
cd build
cmake -DACADOS_WITH_QPOASES=ON ..
make install
pip3 install -e /home/muhammad/acados/interfaces/acados_template
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"/home/muhammad/acados/lib"
export ACADOS_SOURCE_DIR=/home/muhammad/acados
echo $PYTHONPATH
```
/usr/local/lib:/home/muhammad/acados/lib:/home/muhammad/catkin_ws/devel/lib/python2.7/dist-packages:/opt/ros/melodic/lib/python2.7/dist-packages
`muhammad@muhammad-G3-3579:/usr/local/lib$ ls`
python2.7 python3.6 python3.7
`muhammad@muhammad-G3-3579:~/acados/examples/acados_python/getting_started/ocp$ python3 minimal_example_ocp.py`
Traceback (most recent call last):
File “minimal_example_ocp.py”, line 37, in
from acados_template import AcadosOcp, AcadosOcpSolver
ImportError: cannot import name ‘AcadosOcp’

Also when I run   `python3 minimal_example_mhe.py` i get
`ImportError: cannot import name 'AcadosModel'`

I work on Linux Ubuntu 18.04. Thank in advance

**Comment by MuhammadAlhaddad** [comment]
The problem was that  PYTHONPATH doesn't include acados_template directory.
