### ISSUE TITLE
Unit tests do not build with gcc-7.2 (with -Werror)

### ISSUE THREAD

**Issue by nielsvd** [acados/acados#150]
No errors appear with clang and gcc-6.

```
/home/niels/GIT/acados/test/test_utils/read_ocp_qp_in.c: In function ‘read_int_vector_from_txt’:
/home/niels/GIT/acados/test/test_utils/read_ocp_qp_in.c:49:11: error: variable ‘status’ set but not used [-Werror=unused-but-set-variable]
     int_t status, ii;
           ^~~~~~
.
.
.
.
.
```

```
make[2]: *** [test/CMakeFiles/unit_tests.dir/build.make:138: test/CMakeFiles/unit_tests.dir/test_utils/read_ocp_qp_in.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /usr/include/eigen3/Eigen/Core:420:0,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from /home/niels/GIT/acados/test/test_utils/eigen.h:30,
                 from /home/niels/GIT/acados/test/test_utils/read_matrix.h:26,
                 from /home/niels/GIT/acados/test/ocp_qp/test_qpsolvers.cpp:37:
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h: In instantiation of ‘struct Eigen::internal::copy_using_evaluator_traits<Eigen::internal::evaluator<Eigen::Matrix<double, -1, 1> >, Eigen::internal::evaluator<Eigen::Matrix<double, -1, -1> >, Eigen::internal::assign_op<double, double> >’:
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:607:49:   required from ‘class Eigen::internal::generic_dense_assignment_kernel<Eigen::internal::evaluator<Eigen::Matrix<double, -1, 1> >, Eigen::internal::evaluator<Eigen::Matrix<double, -1, -1> >, Eigen::internal::assign_op<double, double>, 0>’
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:739:10:   required from ‘void Eigen::internal::call_dense_assignment_loop(DstXprType&, const SrcXprType&, const Functor&) [with DstXprType = Eigen::Matrix<double, -1, 1>; SrcXprType = Eigen::Matrix<double, -1, -1>; Functor = Eigen::internal::assign_op<double, double>]’
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:879:31:   required from ‘static void Eigen::internal::Assignment<DstXprType, SrcXprType, Functor, Eigen::internal::Dense2Dense, Weak>::run(DstXprType&, const SrcXprType&, const Functor&) [with DstXprType = Eigen::Matrix<double, -1, 1>; SrcXprType = Eigen::Matrix<double, -1, -1>; Functor = Eigen::internal::assign_op<double, double>; Weak = void]’
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:836:49:   required from ‘void Eigen::internal::call_assignment_no_alias(Dst&, const Src&, const Func&) [with Dst = Eigen::Matrix<double, -1, 1>; Src = Eigen::Matrix<double, -1, -1>; Func = Eigen::internal::assign_op<double, double>]’
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:804:27:   required from ‘void Eigen::internal::call_assignment(Dst&, const Src&, const Func&, typename Eigen::internal::enable_if<(! Eigen::internal::evaluator_assume_aliasing<Src>::value), void*>::type) [with Dst = Eigen::Matrix<double, -1, 1>; Src = Eigen::Matrix<double, -1, -1>; Func = Eigen::internal::assign_op<double, double>; typename Eigen::internal::enable_if<(! Eigen::internal::evaluator_assume_aliasing<Src>::value), void*>::type = void*]’
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:782:18:   required from ‘void Eigen::internal::call_assignment(Dst&, const Src&) [with Dst = Eigen::Matrix<double, -1, 1>; Src = Eigen::Matrix<double, -1, -1>]’
/usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:710:32:   required from ‘Derived& Eigen::PlainObjectBase<Derived>::_set(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::Matrix<double, -1, -1>; Derived = Eigen::Matrix<double, -1, 1>]’
/usr/include/eigen3/Eigen/src/Core/Matrix.h:225:24:   required from ‘Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>& Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::operator=(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::Matrix<double, -1, -1>; _Scalar = double; int _Rows = -1; int _Cols = 1; int _Options = 0; int _MaxRows = -1; int _MaxCols = 1]’
/home/niels/GIT/acados/test/ocp_qp/test_qpsolvers.cpp:99:80:   required from here
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:86:63: error: enum constant in boolean context [-Werror=int-in-bool-context]
     MayLinearVectorize = bool(MightVectorize) && MayLinearize && DstHasDirectAccess
.
.
.
```

**Comment by FreyJo** [comment]
It seems like the problem is solved.
